<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Lesley Xu">
<meta name="dcterms.date" content="2023-10-11">

<title>HW2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="HW2_files/libs/clipboard/clipboard.min.js"></script>
<script src="HW2_files/libs/quarto-html/quarto.js"></script>
<script src="HW2_files/libs/quarto-html/popper.min.js"></script>
<script src="HW2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="HW2_files/libs/quarto-html/anchor.min.js"></script>
<link href="HW2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="HW2_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="HW2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="HW2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="HW2_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">HW2</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Lesley Xu </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 11, 2023</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="empirical-section" class="level3">
<h3 class="anchored" data-anchor-id="empirical-section">Empirical Section</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"/Users/lesleyxu/Desktop/Past courses/23AU/ECON 487"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>oj <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"oj.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="visualizing-price" class="level4">
<h4 class="anchored" data-anchor-id="visualizing-price">4) Visualizing price</h4>
<ol type="a">
<li>Make a box plot of price.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(oj, <span class="fu">aes</span>(<span class="fu">factor</span>(brand), price)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">fill =</span> brand))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HW2_files/figure-html/boxplot%20of%20price-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol start="2" type="a">
<li>Make a box plot of log price.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(oj, <span class="fu">aes</span>(<span class="fu">factor</span>(brand), <span class="fu">log</span>(price))) <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">fill =</span> brand))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HW2_files/figure-html/boxplot%20of%20log%20price-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol start="3" type="a">
<li>Make a box plot of price, but separate out each brand.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(oj, <span class="fu">aes</span>(<span class="fu">factor</span>(brand), price)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">fill =</span> brand)) <span class="sc">+</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span> brand)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HW2_files/figure-html/boxplot%20of%20price%20separate-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol start="4" type="a">
<li>Do the same for log price.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(oj, <span class="fu">aes</span>(<span class="fu">factor</span>(brand), <span class="fu">log</span>(price))) <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">fill =</span> brand)) <span class="sc">+</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span> brand)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HW2_files/figure-html/boxplot%20of%20log%20price%20separate-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol start="5" type="a">
<li>What do these graphs tell you about the variation in price? Why do the log plots look different? Do you find them more/less informative?</li>
</ol>
<ul>
<li>The graphs tell me that the prices distribution of dominicks is lowest among the three brands, and tropicana is the highest among those three. Comparing to the original plot, the log plots has all the outliers in the lower bound. When graph the log plots, the data is compressed, causing the effect of spreading out values that were concentrated in the lower range and pulling together values that were widely dispersed in the upper range. Therefore the outliers in the original data become less prominent, and the distribution can appear more symmetrical. The log plot provides more information because the data points are standardized, making it easier for me to compare these three brands in the same scope while keeping the pattern of left-skewed, right-skewed and right-skewed.</li>
</ul>
</section>
<section id="visualizing-the-quantityprice-relationship" class="level4">
<h4 class="anchored" data-anchor-id="visualizing-the-quantityprice-relationship">5) Visualizing the quantity/price relationship</h4>
<ol type="a">
<li><p>Plot logmove (log quantity) vs.&nbsp;log(price) for each brand. For this one the appropriate second part of the ggplot command will be: <code>+ geom_point(aes(color = factor(var_name)))</code></p>
<ol type="i">
<li>What do insights can you derive that were not apparent before?</li>
</ol>
<ul>
<li>The scatterplot tell me a negative correlation between logmove and log(price): as loge move increases, log(price) decreases. The scatterplot also shows a possible linear relationship between logmove and log(price).</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(oj, <span class="fu">aes</span>(logmove, <span class="fu">log</span>(price), <span class="at">alpha =</span> <span class="fl">0.3</span>)) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> <span class="fu">factor</span>(brand)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HW2_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(oj, <span class="fu">aes</span>(logmove, <span class="fu">log</span>(price))) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> <span class="fu">factor</span>(brand))) <span class="sc">+</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span> brand)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="HW2_files/figure-html/unnamed-chunk-1-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div></li>
</ol>
</section>
<section id="estimating-the-relationship." class="level4">
<h4 class="anchored" data-anchor-id="estimating-the-relationship.">6) Estimating the relationship.</h4>
<ol type="a">
<li>Do a regression of log quantity on log price (you can use the lm or glm function to do this). How well does the model fit? What is the elasticity, does it make sense?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>reg1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(logmove <span class="sc">~</span> <span class="fu">log</span>(price), oj)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>reg1_sum <span class="ot">&lt;-</span> <span class="fu">summary</span>(reg1)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>reg1_sum</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = logmove ~ log(price), data = oj)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.0441 -0.5853 -0.0330  0.5756  3.7264 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 10.42342    0.01535  679.04   &lt;2e-16 ***
log(price)  -1.60131    0.01836  -87.22   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9071 on 28945 degrees of freedom
Multiple R-squared:  0.2081,    Adjusted R-squared:  0.2081 
F-statistic:  7608 on 1 and 28945 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><span class="math inline">\(R^2\)</span> for this model is 0.2081, which means 20.81% of the variations in the dependent variable (logmove) could be explained by the independent variable (log(price)) in this model. The elasticity is -1.60131. Price elasticity measures the responsiveness of the quantity demanded of a product to a change in its price. The negative sign of the coefficient indicates an inverse relationship between price and quantity demanded, which makes sense. Besides, <span class="math inline">\(1&lt;|-1.60131|&lt;\infty\)</span> means orange juice is elastic.</li>
</ul>
<ol start="2" type="a">
<li>Now add in an intercept term for each brand (add brand to the regression), how do the results change? How should we interpret these coefficients?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># dummy variables; log(price) change in elasticity</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>reg2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(logmove <span class="sc">~</span> <span class="fu">log</span>(price) <span class="sc">+</span> brand, oj)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>reg2_sum <span class="ot">&lt;-</span> <span class="fu">summary</span>(reg2)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>reg2_sum</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = logmove ~ log(price) + brand, data = oj)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.3152 -0.5246 -0.0502  0.4929  3.5088 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      10.82882    0.01453  745.04   &lt;2e-16 ***
log(price)       -3.13869    0.02293 -136.89   &lt;2e-16 ***
brandminute.maid  0.87017    0.01293   67.32   &lt;2e-16 ***
brandtropicana    1.52994    0.01631   93.81   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7935 on 28943 degrees of freedom
Multiple R-squared:  0.3941,    Adjusted R-squared:  0.394 
F-statistic:  6275 on 3 and 28943 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li>The <span class="math inline">\(R^{2}\)</span> increases from 0.2081 to 0.3941, which means more of the variations could be explained by the new model. The coefficient for log(price) means the elasticity of dominicks products, for every one-unit increase in the log(price), logmove is estimated to decrease by approximately 3.13869 units. the coefficient for brandminute.maid and brandtropicana means minute.maid and tropicana has a higher estimated logmove compare to dominicks when the price is held constant.</li>
</ul>
<ol start="3" type="a">
<li>Now figure out a way to allow the elasticities to differ by brand. Search “interaction terms” and “dummy variables” if you don’t remember this from econometrics. Note the estimate coefficients will “offset” the base estimates. What is the insights we get from this regression? What is the elasticity for each firm? Do the elasticities make sense?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># with logs = elasticities; log(price): elasticity of dominicks</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># elasticity: quantity/price</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>reg3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(logmove <span class="sc">~</span> <span class="fu">log</span>(price) <span class="sc">*</span> brand, oj)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>reg3_sum <span class="ot">&lt;-</span> <span class="fu">summary</span>(reg3)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>reg3_sum</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = logmove ~ log(price) * brand, data = oj)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.4434 -0.5232 -0.0494  0.4884  3.4901 

Coefficients:
                            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                 10.95468    0.02070 529.136   &lt;2e-16 ***
log(price)                  -3.37753    0.03619 -93.322   &lt;2e-16 ***
brandminute.maid             0.88825    0.04155  21.376   &lt;2e-16 ***
brandtropicana               0.96239    0.04645  20.719   &lt;2e-16 ***
log(price):brandminute.maid  0.05679    0.05729   0.991    0.322    
log(price):brandtropicana    0.66576    0.05352  12.439   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7911 on 28941 degrees of freedom
Multiple R-squared:  0.3978,    Adjusted R-squared:  0.3977 
F-statistic:  3823 on 5 and 28941 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li>The elasticity for dominicks is -3.37752, the elasticity for minute.maid is -3.32073, and the elasticity for tropicana is -2.71177. Those elasticities make sense because it matches the price and demand relationships of each individual brand.</li>
</ul>
</section>
<section id="impact-of-featuring-in-store.-the-feat-variable-is-an-indicator-variable-which-takes-the-value-of-one-when-a-product-is-featured-e.g.-like-on-an-endcap-display" class="level4">
<h4 class="anchored" data-anchor-id="impact-of-featuring-in-store.-the-feat-variable-is-an-indicator-variable-which-takes-the-value-of-one-when-a-product-is-featured-e.g.-like-on-an-endcap-display">7) Impact of “featuring in store”. The “feat” variable is an indicator variable which takes the value of one when a product is featured (e.g., like on an endcap display)</h4>
<ol type="a">
<li>What is the average price and featured rate of each brand? Hint: use group_by and summarise within dplyr.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>mean <span class="ot">&lt;-</span> oj <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(brand) <span class="sc">%&gt;%</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">average_price =</span> <span class="fu">mean</span>(price),</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">featured_rate =</span> <span class="fu">mean</span>(feat)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">brand</th>
<th style="text-align: right;">average_price</th>
<th style="text-align: right;">featured_rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">dominicks</td>
<td style="text-align: right;">1.735809</td>
<td style="text-align: right;">0.2570215</td>
</tr>
<tr class="even">
<td style="text-align: left;">minute.maid</td>
<td style="text-align: right;">2.241162</td>
<td style="text-align: right;">0.2885273</td>
</tr>
<tr class="odd">
<td style="text-align: left;">tropicana</td>
<td style="text-align: right;">2.870493</td>
<td style="text-align: right;">0.1662348</td>
</tr>
</tbody>
</table>
</div>
</div>
<ol start="2" type="a">
<li>How should incorporate the feature variable into our regression? Start with an additive formulation (e.g.&nbsp;feature impacts sales, but not through price).</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>reg4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(logmove <span class="sc">~</span> <span class="fu">log</span>(price) <span class="sc">+</span> brand <span class="sc">+</span> feat, oj)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>reg4_sum <span class="ot">&lt;-</span> <span class="fu">summary</span>(reg4)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>reg4_sum</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = logmove ~ log(price) + brand + feat, data = oj)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.7593 -0.4457 -0.0042  0.4306  3.2375 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      10.27909    0.01451  708.22   &lt;2e-16 ***
log(price)       -2.52989    0.02172 -116.50   &lt;2e-16 ***
brandminute.maid  0.68156    0.01177   57.91   &lt;2e-16 ***
brandtropicana    1.30176    0.01483   87.78   &lt;2e-16 ***
feat              0.89062    0.01046   85.13   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7096 on 28942 degrees of freedom
Multiple R-squared:  0.5154,    Adjusted R-squared:  0.5154 
F-statistic:  7696 on 4 and 28942 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ol start="3" type="a">
<li>Now run a model where features can impact sales and price sensitivity (e.g., the model we discussed in class).</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>reg5 <span class="ot">&lt;-</span> <span class="fu">lm</span>(logmove <span class="sc">~</span> <span class="fu">log</span>(price) <span class="sc">*</span> feat, oj)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>reg5_sum <span class="ot">&lt;-</span> <span class="fu">summary</span>(reg5)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>reg5_sum</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = logmove ~ log(price) * feat, data = oj)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.2995 -0.4706  0.0198  0.4950  3.0765 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      9.65926    0.01642  588.27   &lt;2e-16 ***
log(price)      -0.95823    0.01869  -51.27   &lt;2e-16 ***
feat             1.71438    0.03041   56.38   &lt;2e-16 ***
log(price):feat -0.97729    0.04190  -23.32   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7911 on 28943 degrees of freedom
Multiple R-squared:  0.3977,    Adjusted R-squared:  0.3977 
F-statistic:  6371 on 3 and 28943 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ol start="4" type="a">
<li>Now run a model where each brand can have a different impact of being featured and a different impact on price sensitivity. Produce the regression results for this regression brand with brand level elasticities.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>reg6 <span class="ot">&lt;-</span> <span class="fu">lm</span>(logmove <span class="sc">~</span> <span class="fu">log</span>(price) <span class="sc">*</span> brand <span class="sc">*</span> feat, oj)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>reg6_sum <span class="ot">&lt;-</span> <span class="fu">summary</span>(reg6)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>reg6_sum</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = logmove ~ log(price) * brand * feat, data = oj)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.8893 -0.4290 -0.0091  0.4125  3.2368 

Coefficients:
                                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                      10.40658    0.02335 445.668  &lt; 2e-16 ***
log(price)                       -2.77415    0.03883 -71.445  &lt; 2e-16 ***
brandminute.maid                  0.04720    0.04663   1.012    0.311    
brandtropicana                    0.70794    0.05080  13.937  &lt; 2e-16 ***
feat                              1.09441    0.03810  28.721  &lt; 2e-16 ***
log(price):brandminute.maid       0.78293    0.06140  12.750  &lt; 2e-16 ***
log(price):brandtropicana         0.73579    0.05684  12.946  &lt; 2e-16 ***
log(price):feat                  -0.47055    0.07409  -6.351 2.17e-10 ***
brandminute.maid:feat             1.17294    0.08196  14.312  &lt; 2e-16 ***
brandtropicana:feat               0.78525    0.09875   7.952 1.90e-15 ***
log(price):brandminute.maid:feat -1.10922    0.12225  -9.074  &lt; 2e-16 ***
log(price):brandtropicana:feat   -0.98614    0.12411  -7.946 2.00e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.695 on 28935 degrees of freedom
Multiple R-squared:  0.5354,    Adjusted R-squared:  0.5352 
F-statistic:  3031 on 11 and 28935 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ol start="5" type="a">
<li>Now add what you think are the most relevant sociodemographic controls and produce the regression results from that regression as well.<br>
</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>reg7 <span class="ot">&lt;-</span> <span class="fu">lm</span>(logmove <span class="sc">~</span> <span class="fu">log</span>(price) <span class="sc">*</span> brand <span class="sc">*</span> feat <span class="sc">+</span> AGE60 <span class="sc">+</span> EDUC <span class="sc">+</span> ETHNIC <span class="sc">+</span> INCOME <span class="sc">+</span> HHLARGE <span class="sc">+</span> WORKWOM <span class="sc">+</span> HVAL150 <span class="sc">+</span> SSTRDIST <span class="sc">+</span> SSTRVOL <span class="sc">+</span> CPDIST5 <span class="sc">+</span> CPWVOL5, oj)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>reg7_sum <span class="ot">&lt;-</span> <span class="fu">summary</span>(reg7)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>reg7_sum</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = logmove ~ log(price) * brand * feat + AGE60 + EDUC + 
    ETHNIC + INCOME + HHLARGE + WORKWOM + HVAL150 + SSTRDIST + 
    SSTRVOL + CPDIST5 + CPWVOL5, data = oj)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.2004 -0.3922 -0.0049  0.3786  2.9884 

Coefficients:
                                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                      13.143435   0.329622  39.874  &lt; 2e-16 ***
log(price)                       -2.854302   0.036816 -77.528  &lt; 2e-16 ***
brandminute.maid                  0.092348   0.044158   2.091  0.03651 *  
brandtropicana                    0.772280   0.048102  16.055  &lt; 2e-16 ***
feat                              1.055010   0.036034  29.278  &lt; 2e-16 ***
AGE60                             2.044239   0.127506  16.032  &lt; 2e-16 ***
EDUC                              0.955931   0.101486   9.419  &lt; 2e-16 ***
ETHNIC                            0.643102   0.037229  17.274  &lt; 2e-16 ***
INCOME                           -0.279937   0.033300  -8.406  &lt; 2e-16 ***
HHLARGE                          -0.920092   0.230509  -3.992 6.58e-05 ***
WORKWOM                          -0.424559   0.146824  -2.892  0.00384 ** 
HVAL150                           0.357561   0.041803   8.554  &lt; 2e-16 ***
SSTRDIST                         -0.019979   0.001465 -13.634  &lt; 2e-16 ***
SSTRVOL                          -0.055948   0.009768  -5.728 1.03e-08 ***
CPDIST5                           0.064160   0.006289  10.203  &lt; 2e-16 ***
CPWVOL5                          -0.500272   0.025703 -19.464  &lt; 2e-16 ***
log(price):brandminute.maid       0.753984   0.058086  12.981  &lt; 2e-16 ***
log(price):brandtropicana         0.713983   0.053736  13.287  &lt; 2e-16 ***
log(price):feat                  -0.405049   0.070053  -5.782 7.45e-09 ***
brandminute.maid:feat             1.131698   0.077495  14.603  &lt; 2e-16 ***
brandtropicana:feat               0.746656   0.093353   7.998 1.31e-15 ***
log(price):brandminute.maid:feat -1.079118   0.115559  -9.338  &lt; 2e-16 ***
log(price):brandtropicana:feat   -0.989109   0.117302  -8.432  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6568 on 28924 degrees of freedom
Multiple R-squared:  0.5851,    Adjusted R-squared:  0.5848 
F-statistic:  1854 on 22 and 28924 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="overall-analysis" class="level4">
<h4 class="anchored" data-anchor-id="overall-analysis">8) Overall analysis</h4>
<ol type="a">
<li>Based on your work, which brand has the most elastic demand, which as the least elastic?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>elastic_d <span class="ot">&lt;-</span> reg3_sum<span class="sc">$</span>coefficients[[<span class="dv">2</span>]]</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>elastic_t <span class="ot">&lt;-</span> reg3_sum<span class="sc">$</span>coefficients[[<span class="dv">2</span>]] <span class="sc">+</span> reg3_sum<span class="sc">$</span>coefficients[[<span class="dv">6</span>]]</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>elastic_m <span class="ot">&lt;-</span> reg3_sum<span class="sc">$</span>coefficients[[<span class="dv">2</span>]] <span class="sc">+</span> reg3_sum<span class="sc">$</span>coefficients[[<span class="dv">5</span>]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Dominicks has the most elastic demand, tropicana has the least elastic demand.</li>
</ul>
<ol start="2" type="a">
<li>Do the average prices of each good match up with these insights?</li>
</ol>
<ul>
<li>Tropicana has the highest average price, therefore the least elastic demand.</li>
</ul>
<ol start="3" type="a">
<li>Take average prices for each brand. Use the elasticity pricing formula (you can use average values from your analysis above) to “back out” unit costs for each brand. Do the unit costs appear to be the same or different? What are your insights/reactions?</li>
</ol>
<p><span class="math display">\[-\frac{1}{\epsilon} = \frac{P-MC}{P}\]</span> <span class="math display">\[MC_{\text{dominicks}} = 1.735809- \frac{1}{-3.37753} \cdot 1.735809 = 2.249737\]</span> <span class="math display">\[MC_{\text{minute.maid}} = 1.735809- \frac{1}{-3.32073} \cdot 1.735809 = 2.258528\]</span> <span class="math display">\[MC_{\text{tropicana}} = 1.735809- \frac{1}{-2.711769} \cdot 1.735809 = 2.375911\]</span> - Tropicana has the highest unit cost, it matches my insight from previous section (higher average price because of higher unit cost). Such result implies that the consumers of tropicana might be more loyal than dominicks and minute.maid.</p>
</section>
<section id="lets-return-to-the-orange-juice-assignment-and-investigate-how-store-demographics-are-related-to-demand." class="level4">
<h4 class="anchored" data-anchor-id="lets-return-to-the-orange-juice-assignment-and-investigate-how-store-demographics-are-related-to-demand.">9) Let’s return to the orange juice assignment and investigate how store demographics are related to demand.</h4>
<ol type="a">
<li>Take one of the final models from (7) and add in the store demographics as linear features (e.g.&nbsp;+ demo1 + demo2). Report your output.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>reg8 <span class="ot">&lt;-</span> <span class="fu">lm</span>(logmove <span class="sc">~</span> <span class="fu">log</span>(price) <span class="sc">*</span> feat <span class="sc">*</span> brand <span class="sc">+</span> AGE60 <span class="sc">+</span> ETHNIC, oj)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>reg8_sum <span class="ot">&lt;-</span> <span class="fu">summary</span>(reg8)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>reg8_sum</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = logmove ~ log(price) * feat * brand + AGE60 + ETHNIC, 
    data = oj)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.0810 -0.4152 -0.0071  0.4102  2.9652 

Coefficients:
                                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                      10.00348    0.02544 393.173  &lt; 2e-16 ***
log(price)                       -2.82883    0.03794 -74.556  &lt; 2e-16 ***
feat                              1.06932    0.03721  28.736  &lt; 2e-16 ***
brandminute.maid                  0.08632    0.04554   1.896    0.058 .  
brandtropicana                    0.75896    0.04962  15.296  &lt; 2e-16 ***
AGE60                             2.05987    0.06488  31.747  &lt; 2e-16 ***
ETHNIC                            0.49654    0.02139  23.214  &lt; 2e-16 ***
log(price):feat                  -0.42927    0.07235  -5.933 3.01e-09 ***
log(price):brandminute.maid       0.75361    0.05996  12.568  &lt; 2e-16 ***
log(price):brandtropicana         0.71402    0.05550  12.865  &lt; 2e-16 ***
feat:brandminute.maid             1.13604    0.08003  14.195  &lt; 2e-16 ***
feat:brandtropicana               0.75622    0.09642   7.843 4.56e-15 ***
log(price):feat:brandminute.maid -1.07855    0.11937  -9.036  &lt; 2e-16 ***
log(price):feat:brandtropicana   -0.98305    0.12118  -8.112 5.17e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6786 on 28933 degrees of freedom
Multiple R-squared:  0.5571,    Adjusted R-squared:  0.5569 
F-statistic:  2799 on 13 and 28933 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ol start="2" type="a">
<li>What demographics significantly (t-value&gt;2) influence demand?</li>
</ol>
<ul>
<li>AGE60 and ETHNIC significantly influence demand. In section 7e I added all the sociodemographic variables to the regression, among those variables, AGE60 and ETHNIC has the highest t-values, therefore I added those two to my model.</li>
</ul>
<ol start="3" type="a">
<li>Use the predict command to determine how well the model predicts logmove and create a new variable called logmove_hat. To do so construct the “fair <span class="math inline">\(r^{2}\)</span>” covered in class. What is the improvement relative to the model without the demographic features?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>logmove_hat <span class="ot">&lt;-</span> <span class="fu">predict</span>(reg8, oj)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>fair_r2 <span class="ot">&lt;-</span> (<span class="fu">cor</span>(logmove_hat, oj<span class="sc">$</span>logmove))<span class="sc">^</span><span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>The fair_r2 for model with demographic features is 0.557079. Comparing to the model without the demographic features, the model with demographic features has 2.17% more variations of dependent variable could be explained by the independent variable.</li>
</ul>
<ol start="4" type="a">
<li><p>Rather than using fair <span class="math inline">\(r^{2}\)</span> lets now use a test set to determine which model gives the best out of sample prediction.</p>
<ol type="i">
<li>Create a new dataframe which is a random subset of 80% of the data (look at sample_n from the dplyr package).</li>
<li>Estimate the model with and without demographic characteristics. Construct MSE for the training and test set for the models.</li>
<li>Compare the out of sample MSE for the models. Which is lower implying the model does a better job of fitting the data?</li>
</ol></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>trainset <span class="ot">&lt;-</span> <span class="fu">sample_n</span>(oj, <span class="fl">0.8</span> <span class="sc">*</span> <span class="fu">nrow</span>(oj), <span class="at">replace =</span> <span class="cn">FALSE</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>testset <span class="ot">&lt;-</span> oj <span class="sc">%&gt;%</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anti_join</span>(trainset)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>reg_train_with <span class="ot">&lt;-</span> <span class="fu">lm</span>(logmove <span class="sc">~</span> <span class="fu">log</span>(price) <span class="sc">*</span> feat <span class="sc">*</span> brand <span class="sc">+</span> AGE60 <span class="sc">+</span> ETHNIC, trainset)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>logmove_pred_with <span class="ot">&lt;-</span> <span class="fu">predict</span>(reg_train_with, testset)</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>reg_train_without <span class="ot">&lt;-</span> <span class="fu">lm</span>(logmove <span class="sc">~</span> <span class="fu">log</span>(price) <span class="sc">*</span> feat <span class="sc">*</span> brand, trainset)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>logmove_pred_without <span class="ot">&lt;-</span> <span class="fu">predict</span>(reg_train_without, testset)</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a><span class="co"># regress on the train set, use test to predict; manually do the MSE</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>MSE_with_demo <span class="ot">&lt;-</span> <span class="fu">mean</span>((logmove_pred_with <span class="sc">-</span> testset<span class="sc">$</span>logmove)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>MSE_without_demo <span class="ot">&lt;-</span> <span class="fu">mean</span>((logmove_pred_without <span class="sc">-</span> testset<span class="sc">$</span>logmove)<span class="sc">^</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>The model with demographic characteristics has a MSE of 0.4876451, the model without demographic characteristics has a MSE of 0.4650709. Based on my models, the models without demographic characteristics does a better job, probably because demographic characteristics have less influences on logmove than expected.</li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>